### ISSUE TITLE
on the registration we get an error 500

### ISSUE THREAD

**Issue by darthkali** [fh-erfurt/RentATool#132]
I have found this on the server https://rent-a-tool-test.herokuapp.com/
maybe there is an problem with the validation. 

Integer - String cast problem
![image](https://user-images.githubusercontent.com/46423967/87233439-cb017500-c3c7-11ea-8dfb-3f8f26420aff.png)

**Comment by monschey** [comment]
Also bei mir lag es an den Account Daten in der data.sql. Da hat er sich mit den Id´s verhaspelt. Sonst geht die Registration
