### ISSUE TITLE
Fehler in Tool Klasse!

### ISSUE THREAD

**Issue by darthkali** [fh-erfurt/RentATool#23]
Ggf der gleiche Fehler wie im Ticket #22 

![image](https://user-images.githubusercontent.com/46423967/71451524-598a0e00-2778-11ea-8a18-d2bf4df2304f.png)

**Comment by christiankoenig** [comment]
Hatte da lediglich die Meldung das die SDK Version eingestellt werden muss, aber das muss ja jeder bei uns für sich machen. Gab noch nen fehler wegen private zugriff, das hat aber am anfang, vor dem ganzen umbau zeug funktioniert. Ist jetzt erstmal protected....
